groups:
  - arm
  - arm_cartesian

arm:
  planner_type: JointPlanner
  physical_group: arm
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
  kinematics_solver: youbot_arm_kinematics/YouBotArmKinematicsPlugin
  tip_name: arm_link_5
  root_name: arm_link_0
  projection_evaluator: joint_state

arm_cartesian:
  parent_frame: arm_link_0
  physical_group: arm
  planner_type: RPYIKTaskSpacePlanner
  state_spaces:
    - x
    - y
    - z
    - roll
    - pitch
    - yaw
  x:
    type: Linear
    min: -1.0
    max: 1.0
  y:
    type: Linear
    min: -1.0
    max: 1.0
  z:
    type: Linear
    min: -1.0
    max: 1.0
  roll:
    type: Revolute
  pitch:
    type: Revolute
  yaw:
    type: Revolute
  planner_configs:
    - SBLkConfig1
    - LBKPIECEkConfig1
  kinematics_solver: youbot_arm_kinematics/YouBotArmKinematicsPlugin
  tip_name: arm_link_5
  root_name: arm_link_0
  projection_evaluator: joint_state
  longest_valid_segment_fraction: 0.001

planner_configs:
  SBLkConfig1:
    type: kinematic::SBL
  LBKPIECEkConfig1:
    type: kinematic::LBKPIECE